Get a list of problems given a list of problem's ids. [GET] /api/prob…
Judge-Girl/Judge-Girl pull request #211
Opened 2021-04-10 17:43 UTC by timt1028

2021-04-10 17:54 UTC, Wally5077 requested changes
Review done

2021-04-10 17:54 UTC, Wally5077 commented on Problem-Service/src/main/java/tw/waterball/judgegirl/problemservice/domain/usecases/GetProblemListUseCase.java
>  public class GetProblemListUseCase {
add @AllArgsConstructor

2021-04-10 17:54 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +    }
```
 private void saveProblems(int... problemIds) {
        for (int problemId : problemIds) {
            Problem problem = ProblemStubs
                    .problemTemplate()
                    .build();
            problem.setId(problemId);
            byte[] providedCodesZip = ZipUtils.zipFilesFromResources("/stubs/file1.c", "/stubs/file2.c");

            byte[] testcaseIOsZip = ZipUtils.zipFilesFromResources("/stubs/in/", "/stubs/out/");

            problemRepository.save(problem,
                    singletonMap(problem.getLanguageEnv(Language.C), new ByteArrayInputStream(providedCodesZip))
                    , new ByteArrayInputStream(testcaseIOsZip));
        }
    }
```

2021-04-10 17:54 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +        saveProblems(3);
saveProblems(0, 1, 2);

2021-04-10 17:54 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +        saveProblems(1);
saveProblems(0);

2021-04-10 17:55 UTC, Johnny850807 requested changes
Review done

2021-04-10 17:55 UTC, Johnny850807 commented on Problem-Service/src/main/java/tw/waterball/judgegirl/problemservice/domain/repositories/ProblemRepository.java
> +    List<Problem> findProblemsByIds(int[] problemIds);
`List<Problem> findProblemsByIds(int ...problemIds);`

2021-04-10 17:55 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemController.java
> +        if (Objects.nonNull(ids)) {
static import `nonNull`

2021-04-10 17:55 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +    }
Make it look like this

```java
 @Test
    void GivenTProblems_1_2_3_Saved_WhenGetProblemsByIds_1_2_3_ShouldRespond1_2_3() throws Exception {
        saveProblems(1, 2, 3);

        List<Problem> actualProblems = getProblems(1, 2, 3);

        problemsShouldHaveIds(actualProblems, 1, 2, 3);
    }
```

2021-04-10 17:55 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +    }
ditto

2021-04-11 16:14 UTC, Wally5077 approved these changes
LGTM

2021-04-12 07:06 UTC, Johnny850807 requested changes
LGTM, but please try an experiment to improve our previous code. See my comment.

2021-04-12 07:06 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemController.java
>      public List<ProblemItem> getProblems(@RequestParam(value = "tags", required = false) String tagsSplitByCommas,
Does this mean that you can put `String[] tags` here instead of `String tagsSplitByCommas` ?

Try it and tell me the result

2021-04-12 16:21 UTC, Johnny850807 requested changes
Review done

2021-04-12 16:21 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemController.java
> +    public List<ProblemItem> getProblems(@RequestParam(value = "tags", required = false) String[] tagsSplitByCommas,
rename `tagsSplitByCommas` to `tags`

2021-04-12 16:58 UTC, Johnny850807 approved these changes
LGTM

2021-04-13 14:49 UTC, merged