[DELETE] /api/problems/{problemId} archive
Judge-Girl/Judge-Girl pull request #230
Opened 2021-04-17 16:35 UTC by snowmancc

2021-04-17 16:39 UTC, Wally5077 approved these changes
LGTM

2021-04-17 16:48 UTC, Johnny850807 requested changes
REview done.

2021-04-17 16:48 UTC, Johnny850807 commented on Entities/src/main/java/tw/waterball/judgegirl/entities/problem/Problem.java
> +    @NotNull
remove this

also remove the `@NotNull` above the visible property

2021-04-17 16:48 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemController.java
> +    public void deleteProblem(@PathVariable int problemId) {
rename to `archiveOrDeleteProblem`

2021-04-17 16:48 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemController.java
> +    @DeleteMapping(value = "/{problemId}")
@DeleteMapping("/{problemId}")

2021-04-17 16:48 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/repositories/MongoProblemRepository.java
> +    public void deleteProblemById(int problemId) {
rename to `archiveProblemById `

2021-04-17 16:48 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/repositories/MongoProblemRepository.java
> +        update.set("deleted", true);
rename `deleted` to `archived`

2021-04-17 16:48 UTC, Johnny850807 commented on Entities/src/main/java/tw/waterball/judgegirl/entities/problem/Problem.java
> +    private boolean deleted;
rename to `archived`

2021-04-17 16:48 UTC, Johnny850807 commented on Entities/src/main/java/tw/waterball/judgegirl/entities/problem/Problem.java
> +    }
isArchived()

`setArchived(boolean archived)`

2021-04-17 16:48 UTC, Johnny850807 commented on Problem-Service/src/main/java/tw/waterball/judgegirl/problemservice/domain/repositories/ProblemRepository.java
> +    void deleteProblemById(int problemId);
`archiveProblemById`

2021-04-17 16:48 UTC, Johnny850807 commented on Problem-Service/src/main/java/tw/waterball/judgegirl/problemservice/domain/usecases/DeleteProblemUseCase.java
> +public class DeleteProblemUseCase extends BaseProblemUseCase {
You don't need to rename this class

it is `Delete` for sure

2021-04-17 16:48 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +    void GivenOneProblemCreated_WhenDeleteById_ShouldDeleteSuccessfully() throws Exception {
`GivenOneProblemCreated_WhenDeleteIt_ShouldArchiveItSuccessfully`

2021-04-18 08:46 UTC, Johnny850807 commented on API/Problem-API/src/main/java/tw/waterball/judgegirl/problemapi/views/ProblemView.java
> +    public boolean deleted;
rename this to `archived`

2021-04-18 08:46 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +    void GivenOneProblemCreated_WhenDeleteById_ShouldDeleteSuccessfully() throws Exception {
sorry, I mistype this one, should be `GivenOneProblemCreated_WhenArchiveIt_ShouldArchiveItSuccessfully`

2021-04-18 08:50 UTC, Johnny850807 requested changes
Review done

2021-04-18 08:50 UTC, Johnny850807 commented on API/Problem-API/src/main/java/tw/waterball/judgegirl/problemapi/views/ProblemView.java
> +                problem.isDeleted()
is this correct?

this should be `problem.isArchived()`

2021-04-18 08:50 UTC, Johnny850807 commented on API/Problem-API/src/main/java/tw/waterball/judgegirl/problemapi/views/ProblemView.java
> +                .deleted(view.deleted);
??? should be archived

2021-04-22 15:08 UTC, Johnny850807 requested changes
Review done

2021-04-23 13:55 UTC, Johnny850807 approved these changes
LGTM

2021-04-23 13:58 UTC, timt1028 reviewed
LGTM

2021-04-23 14:29 UTC, timt1028 commented
LGTM

2021-04-23 14:31 UTC, merged