[DELETE] /api/exams/{examId} #276
Judge-Girl/Judge-Girl pull request #284
Opened 2021-05-06 16:23 UTC by timt1028

Resolve:#276

2021-05-07 06:56 UTC, Johnny850807 requested changes
Review done

2021-05-07 06:56 UTC, Johnny850807 commented on Domain/Academy/src/main/java/tw/waterball/judgegirl/academy/domain/repositories/ExamRepository.java
>      boolean hasStudentParticipatedExam(int studentId, int examId);
rename this to `isExaminee`

2021-05-07 06:56 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/ExamControllerTest.java
> +    void GivenExamSavedAndGetExam_WhenDeleteExamById_ShouldExamBeNotEmpty() throws Exception {
bad name, the testcase's name should be **narrative**

please improve it yourself for a while

2021-05-07 06:56 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/ExamControllerTest.java
> +        assertTrue(optionalExam.isEmpty());
`assertTrue(examRepository.findById(exam.id).isEmpty())`

2021-05-07 14:59 UTC, Wally5077 requested changes
Review done

2021-05-07 14:59 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Academy/src/main/java/tw/waterball/judgegirl/springboot/academy/repositories/JpaExamRepository.java
> +        jpaExamDAO.deleteById(examId);
```Java
        try {
            jpaExamDAO.deleteById(examId);
        } catch (EmptyResultDataAccessException ignored) {
        }
```

2021-05-08 16:03 UTC, Wally5077 approved these changes
LGTM

2021-05-09 06:45 UTC, Johnny850807 approved these changes
LGTM

2021-05-09 07:28 UTC, merged