Dev/251
Judge-Girl/Judge-Girl pull request #286
Opened 2021-05-07 20:43 UTC by snowmancc

2021-05-08 06:11 UTC, Wally5077 requested changes
Review done

2021-05-08 06:11 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Academy/src/main/java/tw/waterball/judgegirl/springboot/academy/presenters/ExamOverviewPresenter.java
> +    public void showQuestion(Question question, Problem problem) {
我想第一個參數 Question question 可以刪掉 , 並把方法名改成 showProblem

2021-05-08 06:11 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Academy/src/main/java/tw/waterball/judgegirl/springboot/academy/view/ExamHome.java
> +            return builder.build();
```Java
            return QuestionItem.builder()
                    .examId(question.getExamId())
                    .problemId(problem.getId())
                    .quota(question.getQuota())
                    .maxScore(question.getScore())
                    .questionOrder(question.getQuestionOrder())
                    .problemTitle(problem.getTitle()).build();
```
備註 : 這邊有讓你把 problemId 改從 problem 取出 , 請你把 toViewModel 複製來源那邊也一併修掉

2021-05-08 06:11 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/ExamControllerTest.java
> +        assertEquals(firstQuestion.getProblemTitle(), problem.getTitle());
把這段抽成一個方法 , 方便下方可以再次引用

2021-05-08 07:43 UTC, Wally5077 requested changes
Review done

2021-05-08 07:43 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Academy/src/main/java/tw/waterball/judgegirl/springboot/academy/presenters/ExamOverviewPresenter.java
> +    }
```Java
    private List<QuestionItem> aggregateQuestionOverviews() {
        return zipToList(exam.getQuestions(), problems,
                QuestionItem::toViewModel);
    }
```

2021-05-08 08:24 UTC, Wally5077 requested changes

2021-05-08 08:24 UTC, Wally5077 commented on Domain/Academy/src/main/java/tw/waterball/judgegirl/academy/domain/usecases/exam/GetExamOverviewUseCase.java
> +        });
```JAVA
        exam.foreachQuestion(question -> presenter.showQuestion(question, findProblem(question)));
```

2021-05-09 06:34 UTC, Johnny850807 requested changes
Review done

2021-05-09 06:34 UTC, Johnny850807 commented on Domain/Academy/src/main/java/tw/waterball/judgegirl/academy/domain/usecases/exam/GetExamOverviewUseCase.java
> +        void showProblem(Problem problem);
`showQuestion(Question question, Problem problem)`

2021-05-09 06:34 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/main/java/tw/waterball/judgegirl/springboot/academy/view/ExamHome.java
>      }
Don't reuse `ExamHome`

Just create a class `ExamOverview`

2021-05-09 06:34 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/ExamControllerTest.java
> +    }
ditto, use `ExamOverview`

2021-05-09 07:15 UTC, Johnny850807 requested changes
Review done

2021-05-09 07:15 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/main/java/tw/waterball/judgegirl/springboot/academy/view/ExamHome.java
> +        }
remove this

2021-05-09 07:15 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/ExamControllerTest.java
> +    void questionAssertEquals(QuestionView expectedQuestion, ExamOverview.QuestionItem actualQuestion, ProblemView problem) {
`assertQuestionEquals`

2021-05-09 07:24 UTC, Johnny850807 approved these changes
LGTM

2021-05-09 07:38 UTC, merged