Dev/289 [DELETE] /api/homework/{homeworkId} / [GET] /api/homework #289
Judge-Girl/Judge-Girl pull request #293
Opened 2021-05-11 08:47 UTC by ShawnSWu

resoved: #289

2021-05-11 15:19 UTC, Wally5077 requested changes
Review done

2021-05-11 15:19 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/HomeworkControllerTest.java
> +    public void GivenOneHomeworkCreated_WhenDeleteHomeworkById_ShouldRespondSuccessfully() throws Exception {
GivenOneHomeworkCreated_WhenDeleteHomeworkById_ShouldSucceed

2021-05-11 15:19 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/HomeworkControllerTest.java
> +        HomeworkView homework = createHomeworkAndGet(HOMEWORK_NAME);
HomeworkView -> var

2021-05-11 15:19 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/HomeworkControllerTest.java
> +        getHomework(homework.id).andExpect(status().isNotFound());
1. deleteHomework 和 getHomework 中間隔開
2. 把 andExpect(status().isOk()) 放進 deleteHomework
3. getHomework 改成用 assertFalse(homeworkRepository.findHomeworkById(homework.id).isPresent());

2021-05-14 01:25 UTC, timt1028 approved these changes
LGTM

2021-05-14 07:48 UTC, Johnny850807 requested changes
Review done

2021-05-14 07:48 UTC, Johnny850807 commented on Domain/Academy/src/main/java/tw/waterball/judgegirl/academy/domain/usecases/homework/DeleteHomeworkUseCase.java
> +    public void execute(int homeworkId) throws NotFoundException {
no `NotFoundException` is thrown, remove it

2021-05-14 07:48 UTC, Johnny850807 commented on Domain/Academy/src/main/java/tw/waterball/judgegirl/academy/domain/usecases/homework/GetAllHomeworkUseCase.java
> +    public void execute(GetAllHomeworkUseCase.Presenter presenter) throws NotFoundException {
` throws NotFoundException ` ditto

2021-05-14 07:48 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/main/java/tw/waterball/judgegirl/springboot/academy/controllers/HomeworkController.java
> +        return mapToList(allHomework, HomeworkView::toViewModel);
great to see you use it :D

2021-05-14 07:48 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/main/java/tw/waterball/judgegirl/springboot/academy/repositories/JpaHomeworkRepository.java
> +                .collect(toList());
then, here let's go for `mapToList`

2021-05-14 07:48 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/HomeworkControllerTest.java
> +        assertFalse(homeworkRepository.findHomeworkById(homework.id).isPresent());
the human being is more familiar with the positive statement
so change it to

`assertTrue(homeworkRepository.findHomeworkById(homework.id).isEmpty());`

2021-05-14 07:48 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/HomeworkControllerTest.java
> +        });
use `var` instead of the concrete type `List<HomeworkView>` since the types are possibly changed

2021-05-14 07:48 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/HomeworkControllerTest.java
> +    public void GivenManyHomeworkCreated_WhenGetAllHomework_ShouldReturnAllHomework() throws Exception {
`Given3HomeworkCreated_WhenGetAllHomework_ShouldRespondHomeworkListOfSize3`

**Specification by example**, prefer the actual number **3**

2021-05-14 07:48 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/HomeworkControllerTest.java
> +    }
respond the `List<HomeworkView>` in this method

2021-05-14 07:48 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/HomeworkControllerTest.java
> +    }
do `.andExpect(status().isOk());` just in this method

2021-05-14 07:48 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/HomeworkControllerTest.java
> +    private List<HomeworkView> createHomeworkAndGet(int count) throws Exception {
rename `createHomeworkListAndGet`

 to clarify its plurality

2021-05-14 07:48 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/HomeworkControllerTest.java
> +                .forEach(i -> assertEquals(homeworkList.get(i), actualHomeworkList.get(i)));
`assertEquals(homeworkList, actualHomeworkList)`

2021-05-14 07:48 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/HomeworkControllerTest.java
> +    }
```java
return range(0, count)
        .mapToObj(i -> createHomeworkAndGet(HOMEWORK_NAME + i))
        .collect(toList());
```

2021-05-14 13:05 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/HomeworkControllerTest.java
> +        getHomework(homework.id).andExpect(status().isNotFound());
2 還是沒有做到

2021-05-14 13:09 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/HomeworkControllerTest.java
> +        assertEquals(homeworkList.size(), actualHomeworkList.size());
var 還是沒改

2021-05-14 13:14 UTC, Wally5077 requested changes
Review done

2021-05-15 10:32 UTC, Wally5077 approved these changes
LGTM

2021-05-15 10:36 UTC, Johnny850807 requested changes
Review done

2021-05-15 10:36 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/HomeworkControllerTest.java
> +                .forEach(i -> assertEquals(homeworkList.get(i), actualHomeworkList.get(i)));
@ShawnSWu unresolved

2021-05-15 10:36 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/HomeworkControllerTest.java
> +    }
@ShawnSWu unresolved

2021-05-15 13:37 UTC, Johnny850807 requested changes
Review done

2021-05-15 13:37 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/HomeworkControllerTest.java
> +                .forEach(i -> assertEquals(homeworkList.get(i), actualHomeworkList.get(i)));
remove this

2021-05-16 07:35 UTC, Johnny850807 approved these changes
LGTM

2021-05-16 07:35 UTC, merged