Dev/270 [PUT] /api/problems/{problemId}/{langEnv}/providedCodes
Judge-Girl/Judge-Girl pull request #296
Opened 2021-05-14 05:54 UTC by Chaoyuuu

# Description

See the linked issues for the details.

- If you have other implementation details, write it down here.

## Changes

2021-05-14 13:43 UTC, Johnny850807 requested changes
Review done

2021-05-14 13:43 UTC, Johnny850807 commented on Domain/Problem/src/main/java/tw/waterball/judgegirl/problem/domain/repositories/ProblemRepository.java
> +    String updateProblemWithProvidedCodes(Problem problem, Language language, List<FileResource> providedCodes);
`void updateProblemWithProvidedCodes(Problem problem, Language language, List<FileResource> providedCodes);`

2021-05-14 13:43 UTC, Johnny850807 commented on Domain/Problem/src/main/java/tw/waterball/judgegirl/problem/domain/usecases/BaseProblemUseCase.java
> +                .orElseThrow(() -> NotFoundException.notFound(Problem.class).id(problemId));
static import

2021-05-14 13:43 UTC, Johnny850807 commented on Domain/Problem/src/main/java/tw/waterball/judgegirl/problem/domain/usecases/UploadProvidedCodeUseCase.java
> +        presenter.setProvidedCodesFileId(fileId);
`presenter.showResult(problem);`

2021-05-14 13:43 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/repositories/MongoProblemRepository.java
> +    private void updateProvidedCodesFileIdInProblem(Problem problem, String fileId, Language language) {
order consistency : `updateProvidedCodesFileIdInProblem(Problem problem, Language language, String fileId)`

2021-05-14 13:43 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +    void GivenTwoProvidedCodes_WhenUploadProvidedCodes_ShouldResponseProvidedCodesFileId() throws Exception {
`GiveOneProblemSaved_WhenUploadTwoProvidedCodes_ShouldRespondProvidedCodesFileId`

2021-05-14 13:43 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +                .ifPresent(problem -> assertFileIdEquals(fileId, problem, language));
```java
Problem problem = getProblem(problemId);
problemShouldHaveProvidedCodesId(problem, fileId);
```

2021-05-14 13:43 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +    void GivenNotExistedProblemIdAndTwoProvidedCodes_WhenUploadProvidedCodes_ShouldResponseNotFound() throws Exception {
improve this

2021-05-14 13:43 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +
ditto

2021-05-14 13:45 UTC, Wally5077 requested changes
Review done

2021-05-14 13:45 UTC, Wally5077 commented on Domain/Problem/src/main/java/tw/waterball/judgegirl/problem/domain/usecases/UploadProvidedCodeUseCase.java
> +        Problem problem = doFindProblemById(request.problemId);
Problem problem = findProblem(request.problemId);

2021-05-15 05:28 UTC, Wally5077 approved these changes
LGTM

2021-05-15 07:53 UTC, Johnny850807 requested changes
Review done

2021-05-15 07:53 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +    void GiveOneProblemSavedWithNonExistingLanguageEnv_WhenUploadTwoProvidedCodes_ShouldResponseProvidedCodesFileIds() throws Exception {
improve, this is not the given

2021-05-15 07:53 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +    void WhenUploadTwoProvidedCodesWithNonExistingProblemId_ShouldResponseNotFound() throws Exception {
response?

2021-05-15 07:53 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +
no spaces

2021-05-15 07:53 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +                multipart("/api/problems/{problemId}/{langEnvName}/providedCodes", problemId, language.toString());
format

2021-05-15 07:53 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/repositories/MongoProblemRepository.java
> +        if (!fileId.isEmpty()) {
use `StringUtils.isNullOrEmpty` with static import

2021-05-15 07:53 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/repositories/MongoProblemRepository.java
> +    private void removeFileIdIfExist(String fileId) {
rename `removeFileIdIfExists`

2021-05-15 07:53 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/repositories/MongoProblemRepository.java
> +    }
create an issue and add TODO comment for this:
Transaction: Operations in `updateProvidedCodesFileIdInProblem` should be atomic

2021-05-15 11:28 UTC, Johnny850807 approved these changes
Last but not least

2021-05-15 11:28 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +    void GiveOneProblemSavedWithoutLanguageEnv_WhenUploadTwoProvidedCodes_ShouldRespondProvidedCodesFileIds() throws Exception {
`GiveOneProblemSavedWithoutLanguageEnv_WhenUploadTwoProvidedCodes_ShouldRespondProvidedCodesFileId`

2021-05-15 11:33 UTC, merged