If the problem is deleted, its providedCodes and its testcase IOs sho…
Judge-Girl/Judge-Girl pull request #307
Opened 2021-05-16 08:58 UTC by timt1028

resolve #274

2021-05-16 09:50 UTC, Wally5077 requested changes
Review done

2021-05-16 09:50 UTC, Wally5077 commented on Domain/Problem/src/main/java/tw/waterball/judgegirl/problem/domain/repositories/ProblemRepository.java
> +    boolean isFileExistsById(String fileId);
boolean existsFileById(String fileId);

2021-05-16 09:50 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/repositories/MongoProblemRepository.java
> +        }
```Java
    @Override
    public boolean existsFile() {
        return ofNullable(gridFsTemplate.findOne(new Query(where("_id").is(fileId))))
                .map(gridFsTemplate::getResource)
                .map(GridFsResource::exists)
                .orElse(false);
    }
```

2021-05-16 09:50 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/repositories/MongoProblemRepository.java
> +        }
```Java
        findAll().forEach(this::deleteFiles);
```

2021-05-16 09:50 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/repositories/MongoProblemRepository.java
> +        }
1. List fileIds = new LinkedList<>();
2. problem.getLanguageEnvs() 和  problem.getTestcaseIOsFileId() 宣告成一個變數, 型態用 var
3. 這段抽成一個函數 deleteFiles(Problem);

2021-05-16 09:50 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/repositories/MongoProblemRepository.java
> +        Query query = new Query(where("_id").is(problem.getId()));
Query query = query(where("_id").is(problem.getId()))

2021-05-16 09:50 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +        assertTrue(problemRepository.findProblemById(problemId).orElseThrow().isArchived());
這個其他測試案例已經測過了, 所以可以不用留

2021-05-16 09:50 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +        itsShouldBeExist(problem);
這個命名跟你想驗證的結果對不上

2021-05-16 09:50 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +        itsShouldBeNotFounds(problem);
ditto

2021-05-16 09:50 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +        providedCodes.forEach(id -> assertFalse(problemRepository.isFileExistsById(id)));
```Java
        List fileIds = new LinkedList<>();
        List<String> providedCodes = mapToList(problem.getLanguageEnvs().values(),LanguageEnv::getProvidedCodesFileId);
        fileIds.addAll(providedCodes);
        fileIds.add(problem.getTestcaseIOsFileId());
        fileIds.foreach(id->assertTrue(!problemRepository.existsFile(id)));
```

2021-05-17 15:45 UTC, Wally5077 approved these changes
LGTM

2021-05-17 16:45 UTC, Johnny850807 requested changes
Review done

2021-05-17 16:45 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/repositories/MongoProblemRepository.java
> +    public boolean existsFile(String fileId) {
should be a private method

`ProblemRepository` has nothing to do with the file

2021-05-17 16:45 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/repositories/MongoProblemRepository.java
> +                .orElse(false);
delete this method

move 
```java
gridFsTemplate.findOne(new Query(where("_id").is(fileId))))               
 .map(gridFsTemplate::getResource)                
.map(GridFsResource::exists)               
 .orElse(false)
```
to the Integration test

2021-05-17 16:45 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/repositories/MongoProblemRepository.java
> +    private void deleteFiles(Problem problem) {
rename to `deleteProvidedCodesAndTestcaseIOs(Problem problem)`

2021-05-17 16:45 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/repositories/MongoProblemRepository.java
> +        }
the `languageEnvs` can never be null

in order to ensure this
modify Problem's `getLanguageEnvs` as follows
```java
public Map<String, LanguageEnv> getLanguageEnvs() {
        return requireNonNullElse(languageEnvs, emptyMap());;
}
```

2021-05-17 16:45 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +        problemProvidedCodesAndTestcaseIOsShouldBeExist(problem);
delete this testcase

2021-05-17 16:45 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +    }
remove this method

2021-05-17 16:45 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +        fileIds.forEach(fileId -> assertFalse(problemRepository.existsFile(fileId)));
directly use `GridFsTemplate`

2021-05-18 14:59 UTC, Johnny850807 approved these changes
ＬＧＴＭ

2021-05-18 14:59 UTC, merged