Dev/239
Judge-Girl/Judge-Girl pull request #322
Opened 2021-05-18 18:35 UTC by snowmancc

2021-05-19 10:37 UTC, Johnny850807 requested changes
Review done

2021-05-19 10:37 UTC, Johnny850807 commented on Domain/Submission/src/main/java/tw/waterball/judgegirl/submission/domain/repositories/SubmissionRepository.java
> +    List<Submission> findByProblemIdAndExamId(int problemId, int examId);
submission service is unaware of `exam`

2021-05-19 10:37 UTC, Johnny850807 commented on Domain/Submission/src/main/java/tw/waterball/judgegirl/submission/domain/usecases/RejudgeAllSubmissionsUseCase.java
> + * Find a best record submission given a list of submission ids
??

2021-05-19 10:37 UTC, Johnny850807 commented on Domain/Submission/src/main/java/tw/waterball/judgegirl/submission/domain/usecases/RejudgeSubmissionUseCase.java
> +    }
duplicate code in `SubmitCodeUseCase`

2021-05-19 10:37 UTC, Johnny850807 commented on Domain/Submission/src/main/java/tw/waterball/judgegirl/submission/domain/usecases/RejudgeAllSubmissionsUseCase.java
> +        public int examId;
submission service is unaware of `exam`

2021-05-19 10:37 UTC, Johnny850807 commented on Domain/Submission/src/main/java/tw/waterball/judgegirl/submission/domain/usecases/RejudgeSubmissionUseCase.java
> + * Find a best record submission given a list of submission ids
???

2021-05-19 10:37 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/main/java/tw/waterball/judgegirl/springboot/submission/controllers/SubmissionRejudgeController.java
> +@RequestMapping("/api/rejudge")
this is not RESTFul

the rejudge api should be
`/api/submissions/judges`

its request body consists of `problemId` and the `bag query`

2021-05-19 10:37 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/main/java/tw/waterball/judgegirl/springboot/submission/controllers/SubmissionRejudgeController.java
> +        RejudgeAllSubmissionsUseCase.Request request = new RejudgeAllSubmissionsUseCase.Request(examId, problemId);
should be unaware of `exam`

2021-05-19 10:37 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/main/java/tw/waterball/judgegirl/springboot/submission/controllers/SubmissionRejudgeController.java
> +    ResponseEntity rejudgeSubmission(@PathVariable String submissionId) {
respond `void` --> it means ok

2021-05-20 05:05 UTC, Johnny850807 requested changes
Review done

2021-05-20 05:05 UTC, Johnny850807 commented on Domain/Submission/src/main/java/tw/waterball/judgegirl/submission/domain/usecases/dto/SubmissionQueryParams.java
> +        this.queryParameters = queryParameters;
don't use Map, just make its type concrete

**we never use weak types when it's not needed**

2021-05-20 05:05 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/main/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionController.java
> +            queryParameters.put("studentId", String.valueOf(studentId));
ditto

2021-05-20 05:05 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/main/java/tw/waterball/judgegirl/springboot/submission/controllers/SubmissionRejudgeController.java
> +            produces = MediaType.APPLICATION_JSON_VALUE)
redundant, this is default

2021-05-20 05:05 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/main/java/tw/waterball/judgegirl/springboot/submission/controllers/SubmissionRejudgeController.java
> +    void rejudgeAllSubmissions(@RequestParam(value = "page", required = false) Integer page,
why do you need `page` ?

2021-05-20 05:05 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/main/java/tw/waterball/judgegirl/springboot/submission/controllers/SubmissionRejudgeController.java
> +                               @RequestParam Map<String, String> bagQueryParameters) {
no, I didn't say it's from `query param`, I said it's from the `body`

2021-05-20 05:05 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/main/java/tw/waterball/judgegirl/springboot/submission/controllers/SubmissionRejudgeController.java
> +            produces = MediaType.APPLICATION_JSON_VALUE)
redundant

2021-05-20 05:05 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +//        givenSubmission(submission("A").RE(2, 200).bag("exam-id", "1").build(STUDENT1_ID, problem.getId(), Language.C.toString()));
remove unnecessary comments

2021-05-20 05:05 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +    }
You didn't test it strictly

2021-05-20 05:05 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +                .andExpect(status().isOk());
You didn't test it strictly

2021-05-20 05:05 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +    void GivenSubmission_WhenRejudgeOne_ShouldRespondSuccessfully() throws Exception {
`GivenOneSubmission_WhenRejudgeThatSubmission_ShouldHaveNewRejudgeDeployed`

2021-05-20 05:05 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +    void GivenThreeSubmission_WhenRejudgeAll_ShouldRespondSuccessfully() throws Exception {
`GivenThreeSubmissionsInAQuestion_WhenRejudgeThoseSubmissionsUnderTheQuestion_ShouldHaveThreeRejudgeDeployed`

2021-05-20 05:24 UTC, Johnny850807 requested changes
Review done

2021-05-20 05:24 UTC, Johnny850807 commented on Domain/Submission/src/main/java/tw/waterball/judgegirl/submission/domain/usecases/GetBestSubmissionUseCase.java
> +                queryParameters, Collections.emptyMap());
don't do this, .... what the heck

2021-05-20 05:24 UTC, Johnny850807 commented on Domain/Submission/src/main/java/tw/waterball/judgegirl/submission/domain/usecases/RejudgeAllSubmissionsUseCase.java
> +    }
I don't think this class is necessary

why not just use `RejudgeSubmissionsUseCase` to handle it?
(remember to rename `RejudgeSubmissionUseCase` to `RejudgeSubmissionsUseCase`)

2021-05-20 05:32 UTC, Wally5077 requested changes
Review done

2021-05-20 05:32 UTC, Wally5077 commented on Domain/Submission/src/main/java/tw/waterball/judgegirl/submission/domain/usecases/GetBestSubmissionUseCase.java
> +                queryParameters, Collections.emptyMap());
為什麼改成了 map ?

2021-05-20 05:32 UTC, Wally5077 commented on Domain/Submission/src/main/java/tw/waterball/judgegirl/submission/domain/usecases/RejudgeAllSubmissionsUseCase.java
> + * Find a best record submission given a list of submission ids
Find a best record submission given a list of submission id < 這是什麼？

2021-05-20 05:32 UTC, Wally5077 commented on Domain/Submission/src/main/java/tw/waterball/judgegirl/submission/domain/usecases/RejudgeAllSubmissionsUseCase.java
> +    public static class Request {
為什麼開了一個 Request 類別？

2021-06-10 06:52 UTC, Wally5077 requested changes
Review done

2021-06-10 06:52 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Submission/src/main/java/tw/waterball/judgegirl/springboot/submission/controllers/SubmissionRejudgeController.java
> +                               @RequestParam Map<String, String> bagQueryParameters) {
Map<String, String> -> Bag

2021-06-10 06:52 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +        request.setProblemId(problem.getId());
var request = RejudgeSubmissionsUseCase.Request(problem.getId());

2021-06-10 06:52 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +        assertEquals(submissions3.submittedCodesFileId, submissions4.submittedCodesFileId);
這邊重複了，抽出一個叫 assertSubmittedCodesEquals(Token token) 的方法吧
getSubmissionsInPage 需要的 studentId 可以從 token.getStudentId(); 取得

2021-06-10 16:58 UTC, Wally5077 requested changes
Review done

2021-06-10 16:58 UTC, Wally5077 commented on Domain/Submission/src/main/java/tw/waterball/judgegirl/submission/domain/usecases/RejudgeSubmissionsUseCase.java
> +        }
@NoArgsConstructor

2021-06-10 16:58 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Submission/src/main/java/tw/waterball/judgegirl/springboot/submission/controllers/SubmissionRejudgeController.java
> +    void rejudgeAllSubmissions(@RequestBody RejudgeSubmissionsUseCase.Request request,
RejudgeSubmissionsUseCase.Request increase a parameter 'Bag submissionBag'

2021-06-10 16:58 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Submission/src/main/java/tw/waterball/judgegirl/springboot/submission/controllers/SubmissionRejudgeController.java
> +    @PostMapping(value = "/judges")
@PostMapping("/judges")

2021-06-10 16:58 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Submission/src/main/java/tw/waterball/judgegirl/springboot/submission/controllers/SubmissionRejudgeController.java
> +    @PostMapping(value = "/{submissionId}/judge")
ditto

2021-06-10 16:58 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +    private void assertSubmittedCodesEquals(TokenService.Token token) throws Exception {
1. static import TokenService.Token 
2. 將這方法移到最下面

2021-06-10 16:58 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +                toJson(new Bag() {{
new Bag("examId", "1");

2021-06-10 17:23 UTC, Johnny850807 requested changes
Review done

2021-06-10 17:23 UTC, Johnny850807 commented on Domain/Submission/src/main/java/tw/waterball/judgegirl/submission/domain/usecases/SubmitCodeUseCase.java
> +    public void execute(Submission originalSubmission) throws SubmissionThrottlingException {
Rename `originalSubmission` to `submission`
 `SubmitCodeUseCase` assumes that the incoming `submission` should be a new one which doesn't have ID and the verdict. (So you need to clear them in the rejudge usecase.)

2021-06-10 17:23 UTC, Johnny850807 commented on Domain/Submission/src/main/java/tw/waterball/judgegirl/submission/domain/usecases/SubmitCodeUseCase.java
> +    private void mayDeployJudgerAndPublishEvent(Problem problem, Submission submission) {
`mayDeployJudgerAndPublishEvents`

2021-06-10 17:23 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +    void GiveSubmitCodeWithAdminToken_WhenRejudgeThatSubmissionAndGetThatStudentSubmissions_ShouldGetTwoSubmissionWhitTheSameFileId() throws Exception {
`GivenAStudentHasOneSubmission_WhenRejudgeThatSubmission_ThenTheStudentShouldHaveTwoSubmissionsWithTheSameFileIds`

2021-06-10 17:23 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +        assertSubmittedCodesEquals(ADMIN_TOKEN);
allOfTheStudentSubmissionsShouldHaveTheSameFileIds(TokenService.Token token)

2021-06-10 17:23 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +    void GiveSubmit2CodeWithAdmin2Token_WhenRejudgeAllSubmissionsAndRespectivelyGetTwoStudentSubmissions_ShouldGetTwoGroupsSubmissionWhitTheSameFileId() throws Exception {
`GivenTwoSubmissionsOfAQuestionFrom2Admins_WhenRejudgeAllSubmissionsOfThatQuestion_SubmissionsOfBothAdminsShouldHaveTheSameFileIds`

2021-06-10 17:23 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +                }}).getBytes(UTF_8));
No need for `Part`, put it in the body

2021-06-10 17:23 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +        assertSubmittedCodesEquals(ADMIN_TOKEN2);
304th line's space is redundant

2021-06-11 04:32 UTC, Johnny850807 requested changes
Review done

2021-06-11 04:32 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/main/java/tw/waterball/judgegirl/springboot/submission/controllers/SubmissionRejudgeController.java
> +    void rejudgeAllSubmissions(@RequestBody Request request) {
rename to `rejudgeSubmissions`

2021-06-11 04:32 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +    }
Sorry, the test is still not strict enough.

You should test whether the judger has been deployed

2021-06-11 04:32 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +    void GivenAStudentHasOneSubmission_WhenRejudgeThatSubmission_ThenTheStudentShouldHaveTwoSubmissionsWithTheSameFileIds() throws Exception {
rename `GivenAStudentHasOneSubmission_WhenRejudgeThatSubmission_ThenTheJudgerShouldBeDeployedAndStudentShouldHaveTwoSubmissionsWithTheSameFileIds `

2021-06-11 04:32 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +    void GivenTwoSubmissionsOfAQuestionFrom2Admins_WhenRejudgeAllSubmissionsOfThatQuestion_SubmissionsOfBothAdminsShouldHaveTheSameFileIds() throws Exception {
rename to `GivenTwoSubmissionsOfAQuestionFrom2Admins_WhenRejudgeAllSubmissionsOfThatQuestion_Then2JudgersAreDeployedAndSubmissionsOfBothAdminsShouldHaveTheSameFileIds`

2021-06-11 04:32 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +        var afterRejudgeSubmissions = getSubmissionsInPage(token.getStudentId(), token, 0);
rename to `submissions`

2021-06-11 04:32 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +        assertEquals(submissions1.submittedCodesFileId, submissions2.submittedCodesFileId);
do for-loop, why can you assume that student has only two submissions?

2021-06-11 08:26 UTC, Wally5077 approved these changes
LGTM

2021-06-13 16:29 UTC, Johnny850807 requested changes
Review done

2021-06-13 16:29 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +    }
```java
assertTrue(submissions.stream()
    .map(SubmissionView::getSubmittedCodesFileId)
    .distinct().count() == 1);
```

2021-06-13 16:29 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/AbstractSubmissionControllerTest.java
> +        ArgumentCaptor<Submission> submissionArgumentCaptor = ArgumentCaptor.forClass(Submission.class);
var

2021-06-13 16:29 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Submission/src/test/java/tw/waterball/judgegirl/springboot/submission/controllers/StudentSubmissionControllerTest.java
> +        allOfTheStudentSubmissionsShouldHaveTheSameFileIds(ADMIN_TOKEN2);
```java
var submissions = submissionRepository.query(SubmissionQueryParams.EMPTY);
assertEquals(4, submissions.size());
allSubmissionsShouldDeployJudger(submissions);        allOfTheStudentSubmissionsShouldHaveTheSameFileIds(ADMIN_TOKEN);    
allOfTheStudentSubmissionsShouldHaveTheSameFileIds(ADMIN_TOKEN2);
```

2021-06-14 12:57 UTC, Johnny850807 requested changes
Review done.

2021-06-14 12:57 UTC, Johnny850807 commented on Domain/Primitives/src/main/java/tw/waterball/judgegirl/primitives/submission/Bag.java
> +    public static final Bag EMPTY = new Bag();
1. make it immutable.
2. respond this bag in the `empty` method

2021-06-14 12:57 UTC, Johnny850807 commented on Domain/Submission/src/main/java/tw/waterball/judgegirl/submission/domain/usecases/query/SubmissionQueryParams.java
> +    public static final SubmissionQueryParams EMPTY = new SubmissionQueryParams
`return SubmissionQueryParams.builder().build();`

2021-06-25 17:08 UTC, Johnny850807 approved these changes
LGTM

2021-06-25 17:11 UTC, merged