[Delete] /api/problems/{problemId}/testcases/{testcaseId} #310
Judge-Girl/Judge-Girl pull request #331
Opened 2021-05-20 18:44 UTC by ShawnSWu

Resolved #310

2021-05-21 06:39 UTC, Johnny850807 requested changes
Review done

2021-05-21 06:39 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemController.java
> +
do **AUTH** (admin-only), see other methods for reference

2021-05-21 06:39 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +    void GivenProblemSaved_WhenDeleteTestcase_ThenShouldDeleteSuccessfully() throws Exception {
`GivenProblemSavedWithTestcases_WhenDeleteOneOfItsTestcase_ThenShouldDeleteSuccessfully`

2021-05-21 06:39 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
> +        assertEquals(problem.getTestcases().size() - 1, actualTestcases.size());
validate more strictly --> make sure the correct testcase is deleted

2021-05-21 06:39 UTC, Johnny850807 commented on Domain/Problem/src/main/java/tw/waterball/judgegirl/problem/domain/usecases/DeleteTestcaseUseCase.java
> +    @Builder
don't use Builder when there are just 1~3 parameters

2021-05-21 06:39 UTC, Johnny850807 commented on Domain/Problem/src/main/java/tw/waterball/judgegirl/problem/domain/usecases/DeleteTestcaseUseCase.java
> +    public void execute(Request request) throws NotFoundException {
no NotFoundException is thrown

2021-05-21 06:39 UTC, Johnny850807 commented on Domain/Problem/src/main/java/tw/waterball/judgegirl/problem/domain/usecases/DeleteTestcaseUseCase.java
> +    public DeleteTestcaseUseCase(ProblemRepository testCaseRepository) {
use lombok

2021-05-21 10:03 UTC, Wally5077 reviewed
Review done

2021-07-09 13:48 UTC, Wally5077 approved these changes
LGTM

2021-07-10 08:29 UTC, Johnny850807 approved these changes
LGTM

2021-07-10 14:48 UTC, merged