Download CSV file for exam's scores
Judge-Girl/Judge-Girl pull request #386
Opened 2021-07-11 21:58 UTC by snowmancc

2021-07-12 06:50 UTC, timt1028 commented on Spring-Boot/Spring-Boot-Academy/src/main/java/tw/waterball/judgegirl/springboot/academy/controllers/ExamController.java
> +            produces = "application/csv")
Maybe merge one Line @GetMapping(value = "/exams/{examId}/transcript/csv", produces = "application/csv")

2021-07-12 07:49 UTC, Johnny850807 requested changes
Review done

2021-07-12 07:49 UTC, Johnny850807 commented on Domain/Academy/src/main/java/tw/waterball/judgegirl/academy/domain/usecases/exam/CreateExamTranscriptUseCase.java
> +                .collect(toList());
Don't throw `NotFoundException`, please just include the problems that exist.

2021-07-12 07:49 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/pom.xml
> +            <version>1.8</version>
Don't put the version here, please specify the version in the `Dependencies/pom.xml`

2021-07-12 07:49 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/main/java/tw/waterball/judgegirl/springboot/academy/controllers/ExamController.java
> +            return ResponseEntityUtils.respondInputStreamResource(presenter.present());
static import

2021-07-12 07:49 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/main/java/tw/waterball/judgegirl/springboot/academy/presenters/ExamTranscriptCsvFilePresenter.java
> +}
Clean Code: Please put the invoked methods below the invoker method

2021-07-12 07:49 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/main/java/tw/waterball/judgegirl/springboot/academy/presenters/ExamTranscriptCsvFilePresenter.java
> +        }
@SneakyThrows

2021-07-12 07:49 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/main/java/tw/waterball/judgegirl/springboot/academy/presenters/ExamTranscriptCsvFilePresenter.java
> +            Student student = examineeRecord.getExaminee();
rename `student` to `examinee`

2021-07-12 07:49 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/main/java/tw/waterball/judgegirl/springboot/academy/presenters/ExamTranscriptCsvFilePresenter.java
> +            ByteArrayInputStream inStream = new ByteArrayInputStream(out.toByteArray());
rename `inStream` to `in`

2021-07-12 07:49 UTC, Johnny850807 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/ExamControllerTest.java
> +        Map<String, TranscriptView.ExamineeRecordView> scoreBoard = transcript.scoreBoard;
var scoreBoard = transcript.scoreBoard;

2021-07-12 09:05 UTC, Wally5077 requested changes
Review done

2021-07-12 09:05 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/ExamControllerTest.java
> +                .parse(in);
Iterable<CSVRecord> records -> var records

2021-07-12 09:12 UTC, Wally5077 requested changes

2021-07-12 09:12 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Academy/src/main/java/tw/waterball/judgegirl/springboot/academy/presenters/ExamTranscriptCsvFilePresenter.java
> +    private List<List<String>> createExamTranscriptCsvBody(List<ExamineeRecord> examineeRecords) {
```Java
    private List<List<String>> createExamTranscriptCsvBody(List<ExamineeRecord> examineeRecords) {
        return mapToList(examineeRecords, this::examTranscriptCsvRows);
    }

    private List<String> examTranscriptCsvRows(ExamineeRecord examineeRecord) {
        return flatMapToList(of(examineeCsvBodyRows(examineeRecord),
                questionScoreCsvBodyRows(problems, examineeRecord)), Collection::stream);
    }

    private List<String> examineeCsvBodyRows(ExamineeRecord examineeRecord) {
        var examinee = examineeRecord.getExaminee();
        return of(examinee.getName(), examinee.getEmail());
    }

    private List<String> questionScoreCsvBodyRows(Collection<ProblemView> problems,
                                                  ExamineeRecord examineeRecord) {
        List<String> scoreRows = new ArrayList<>(1 + problems.size());
        var questionScores = questionScores(examineeRecord);
        int totalScore = 0;
        for (var problem : problems) {
            int score = questionScores.get(problem.id);
            scoreRows.add(String.valueOf(score));
            totalScore += score;
        }
        scoreRows.add(String.valueOf(totalScore));
        return scoreRows;
    }

    private GetById<Integer, Integer> questionScores(ExamineeRecord examineeRecord) {
        var questionRecords = examineeRecord.getQuestionRecords();
        var questionScores = toMap(questionRecords,
                questionRecord -> questionRecord.getQuestion().getProblemId(),
                CreateExamTranscriptUseCase.QuestionRecord::calculateScore);
        return questionScores::get;
    }

    public FileResource present() {
        try (var out = new ByteArrayOutputStream()) {
            var csvPrinter = new CSVPrinter(new PrintWriter(out, false, UTF_8),
                    CSVFormat.DEFAULT.withHeader(createExamTranscriptCsvHeader(problems)));

            var csvBody = createExamTranscriptCsvBody(examineeRecords);
            for (List<String> record : csvBody) {
                csvPrinter.printRecord(record);
            }
            csvPrinter.flush();

            var in = new ByteArrayInputStream(out.toByteArray());
            return new FileResource(EXAM_TRANSCRIPT_FILE_NAME, out.size(), in);
        } catch (IOException e) {
            throw new RuntimeException("Create csv file of exam transcript error", e);
        }
    }
```

2021-07-13 07:52 UTC, Wally5077 requested changes
Review done

2021-07-13 07:52 UTC, Wally5077 commented on API/Problem-API/src/main/java/tw/waterball/judgegirl/problemapi/clients/RestProblemApiClient.java
> +            String idsSplitByComma = ids.stream().map(String::valueOf).collect(joining(","));
這一段我認為可以放在 StreamUtils ，多開 join 方法寫這段邏輯
ids.stream().map(String::valueOf).collect(joining(","));

2021-07-13 07:52 UTC, Wally5077 commented on API/Problem-API/src/main/java/tw/waterball/judgegirl/problemapi/clients/RestProblemApiClient.java
> +            String url = parsePath(API_PREFIX + "?ids=", idsSplitByComma);
多載 parsePath(url, map)，使它支援 query parameters

2021-07-13 09:48 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Academy/src/main/java/tw/waterball/judgegirl/springboot/academy/presenters/ExamTranscriptCsvFilePresenter.java
> +    }
最後還是改用 Map 好了，這樣可以直接使用 Map.getOrDefault(key, defaultValue)，確保一定有資料

```Java
private List<String> questionScoreCsvBodyRows(Collection<ProblemView> problems,
                                                  ExamineeRecord examineeRecord) {
        List<String> scoreRows = new ArrayList<>(1 + problems.size());
        var questionScores = questionScores(examineeRecord);
        int totalScore = 0;
        for (var problem : problems) {
            int score = questionScores.getOrDefault(problem.id, 0);
            scoreRows.add(String.valueOf(score));
            totalScore += score;
        }
        scoreRows.add(String.valueOf(totalScore));
        return scoreRows;
    }

    private Map<Integer, Integer> questionScores(ExamineeRecord examineeRecord) {
        var questionRecords = examineeRecord.getQuestionRecords();
        return toMap(questionRecords,
                questionRecord -> questionRecord.getQuestion().getProblemId(),
                CreateExamTranscriptUseCase.QuestionRecord::calculateScore);
    }
```

2021-07-24 18:00 UTC, Wally5077 approved these changes
LGTM

2021-07-25 03:26 UTC, timt1028 reviewed
LGTM

2021-07-25 03:27 UTC, timt1028 approved these changes
LGTM

2021-07-25 06:35 UTC, Johnny850807 requested changes
Wait for CI's pass

2021-08-11 08:24 UTC, merged