Dev/400: patch testcase IO
Judge-Girl/Judge-Girl pull request #402
Opened 2021-09-25 17:13 UTC by Johnny850807

resolve: #400
Dev/400: patch testcase IO

2021-09-25 17:16 UTC, Johnny850807 commented on Commons/src/main/java/tw/waterball/judgegirl/commons/utils/ZipUtils.java
> +    public static void zipFromFile(File[] files, OutputStream out, Predicate<String> ignoredFilePredicate) {
Make it more useful and support more cases.

2021-09-26 07:01 UTC, Chaoyuuu approved these changes
LGTM

2021-09-26 07:59 UTC, Wally5077 requested changes
Review done

2021-09-26 07:59 UTC, Wally5077 commented on Domain/Problem/src/main/java/tw/waterball/judgegirl/problem/domain/repositories/ProblemRepository.java
> +            return Optional.ofNullable(stdIn);
static import ```ofNullable```

2021-09-26 07:59 UTC, Wally5077 commented on Domain/Problem/src/main/java/tw/waterball/judgegirl/problem/domain/repositories/ProblemRepository.java
> +            return Optional.ofNullable(stdOut);
ditto

2021-09-26 07:59 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Problem/src/main/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemController.java
> +                new HashSet<>(convertMultipartFilesToFileResources(outFiles))
```Java
Set.copyOf(convertMultipartFilesToFileResources(inFiles));
Set.copyOf(convertMultipartFilesToFileResources(outFiles));
```

2021-09-26 07:59 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
>          return ofNullable(gridFsTemplate.findOne(new Query(where("_id").is(fileId))))
```Java
return ofNullable(gridFsTemplate.findOne(query(where("_id").is(fileId))))
```

2021-09-28 16:26 UTC, Wally5077 requested changes
Review done

2021-09-28 16:26 UTC, Wally5077 commented on Domain/Problem/src/main/java/tw/waterball/judgegirl/problem/domain/usecases/DownloadTestCaseIOsUseCase.java
> +                .orElseThrow(() -> new NotFoundException(String.format("The testcase's IO is not found. (problemId=%d, testcaseId=%s) " +
static import ```String.format()```

2021-09-28 16:26 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Problem/src/test/java/tw/waterball/judgegirl/springboot/problem/controllers/ProblemControllerTest.java
>          }
```fileIds..forEach(fileId -> assertTrue(fileShouldExist(fileId), message));```

2021-10-04 06:07 UTC, Johnny850807 commented on Domain/Problem/src/main/java/tw/waterball/judgegirl/problem/domain/usecases/DownloadTestCaseIOsUseCase.java
> +                .orElseThrow(() -> new NotFoundException(String.format("The testcase's IO is not found. (problemId=%d, testcaseId=%s) " +
Needn't

2021-10-04 06:46 UTC, Wally5077 approved these changes
LGTM

2021-10-04 10:09 UTC, merged