Dev/385 [POST] /api/groups/{groupId}/homework/{homeworkId}/progress && [POST]…
Judge-Girl/Judge-Girl pull request #427
Opened 2021-10-25 14:53 UTC by sh910913

resolve: #385

2021-10-26 08:45 UTC, wallychen0705 requested changes
Review done

2021-10-28 09:53 UTC, wallychen0705 requested changes
Review done

2021-11-03 04:03 UTC, Chaoyuuu requested changes
Review done!
To follow the rule of ubiquitous language, we don't have `question` in this context.
Please rename all `question` to `problem`.

2021-11-07 13:08 UTC, sh910913 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/HomeworkControllerTest.java
> +        return groupRepository.save(group);
It is not work.
got IllegalStateException: You can't save the group with its memberships at the same time.
![image](https://user-images.githubusercontent.com/29350642/140646154-00f96b58-8f77-44db-8ec4-cf20b9123a7e.png)

2021-11-09 08:17 UTC, Wally5077 commented on Domain/Academy/src/main/java/tw/waterball/judgegirl/academy/domain/usecases/homework/GetGroupsHomeworkProgressUseCase.java
> +    }
@sh910913

2021-11-09 08:27 UTC, sh910913 commented on Domain/Academy/src/main/java/tw/waterball/judgegirl/academy/domain/usecases/homework/GetGroupsHomeworkProgressUseCase.java
> +    }
@Wally5077 這個已經有改過了喔。

2021-11-13 08:46 UTC, Wally5077 requested changes
Review done

2021-11-13 08:46 UTC, Wally5077 commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/HomeworkControllerTest.java
> +    }
This should be amended.

2021-11-13 12:48 UTC, Wally5077 requested changes
Review done

2021-11-13 13:17 UTC, Chaoyuuu requested changes
Review done!

2021-11-13 16:10 UTC, Chaoyuuu requested changes
Review done. Thanks.

2021-11-13 16:10 UTC, Chaoyuuu commented on Domain/Academy/src/main/java/tw/waterball/judgegirl/academy/domain/usecases/homework/HomeworkProgressPresenter.java
> + * @version 创建时间：2021/11/13 10:33 PM
please remove this line. :rofl:

2021-11-13 16:10 UTC, Chaoyuuu commented on Domain/Academy/src/main/java/tw/waterball/judgegirl/academy/domain/usecases/homework/StudentSubmissionRecord.java
> + * @version 创建时间：2021/11/13 10:44 PM
ditto

2021-11-13 16:10 UTC, Chaoyuuu commented on Spring-Boot/Spring-Boot-Academy/src/test/java/tw/waterball/judgegirl/springboot/academy/controllers/HomeworkControllerTest.java
> +    @DisplayName("Given a homework consists of two problems [p1, p2] and two students [A, B, C]," +
1. ... `and three students [A, B, C]`
2. you miss the context "group students to the group"

2021-11-14 16:55 UTC, Wally5077 approved these changes
LGTM

2021-11-16 03:21 UTC, Chaoyuuu approved these changes
LGTM! Thanks! 😊

2021-11-16 09:09 UTC, merged